In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("data/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df_cls = df.drop(["PassengerId","Name","Ticket","Cabin","SibSp","Parch","Embarked"],axis=1,errors="ignore")
df_cls.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [4]:
df_cls["Sex"] = df_cls["Sex"].astype("category").cat.codes
df_cls.head()

   Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500

In [5]:
df_cls.info()
df_cls.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int8
 3   Age       714 non-null    float64
 4   Fare      891 non-null    float64
dtypes: float64(2), int64(2), int8(1)
memory usage: 28.8 KB

         Survived      Pclass         Sex         Age        Fare
count  891.000000  891.000000  891.000000  714.000000  891.000000
mean     0.383838    2.308642    0.647587   29.699118   32.204208
std      0.486592    0.836071    0.477990   14.526497   49.693429
min      0.000000    1.000000    0.000000    0.420000    0.000000
25%      0.000000    2.000000    0.000000   20.125000    7.910400
50%      0.000000    3.000000    1.000000   28.000000   14.454200
75%      1.000000    3.000000    1.000000   38.000000   31.000000
max      1.000000    3.000000    1.000000   80.000000  512.329200

In [6]:
df_cls.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [7]:
df_cls["Age"] = df_cls["Age"].fillna(df_cls["Age"].mean()).astype("int")

In [8]:
df_cls[df_cls["Age"].isnull()]

Empty DataFrame
Columns: [Survived, Pclass, Sex, Age, Fare]
Index: []

In [9]:
df_rescaled = df_cls
df_rescaled.head()

   Survived  Pclass  Sex  Age     Fare
0         0       3    1   22   7.2500
1         1       1    0   38  71.2833
2         1       3    0   26   7.9250
3         1       1    0   35  53.1000
4         0       3    1   35   8.0500

In [10]:
for i in range(df_rescaled.shape[1]):
    mean = df_rescaled.iloc[:, i].mean()
    max_ = df_rescaled.iloc[:, i].max()
    min_ = df_rescaled.iloc[:, i].min()
    if max_ != min_:
        df_rescaled.iloc[:,i] = (df_rescaled.iloc[:,i] - mean) / (max_ - min_)
    else:
        df_rescaled.iloc[:,i]= 0
df_rescaled.head()

C:\Users\simoo\AppData\Local\Temp\ipykernel_14556\1792267865.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0     -0.383838
1      0.616162
2      0.616162
3      0.616162
4     -0.383838
         ...
886   -0.383838
887    0.616162
888   -0.383838
889    0.616162
890   -0.383838
Name: Survived, Length: 891, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_rescaled.iloc[:,i] = (df_rescaled.iloc[:,i] - mean) / (max_ - min_)
C:\Users\simoo\AppData\Local\Temp\ipykernel_14556\1792267865.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0      0.345679
1     -0.654321
2      0.345679
3     -0.654321
4      0.345679
         ...
886   -0.154321
887   -0.654321
888    0.345679
889   -0.654321
890    0.345679
Name: Pclass, Length: 891, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_rescaled.iloc[:,i] = (df_rescaled.iloc[:,i] - mean) / (max_ - min_)
C:\Users\simoo\AppData\Local\Temp\ipykernel_14556\1792267865.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0      0.352413
1     -0.647587
2     -0.647587
3     -0.647587
4      0.352413
         ...
886    0.352413
887   -0.647587
888   -0.647587
889    0.352413
890    0.352413
Name: Sex, Length: 891, dtype: float64' has dtype incompatible with int8, please explicitly cast to a compatible dtype first.
  df_rescaled.iloc[:,i] = (df_rescaled.iloc[:,i] - mean) / (max_ - min_)
C:\Users\simoo\AppData\Local\Temp\ipykernel_14556\1792267865.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0     -0.094304
1      0.105696
2     -0.044304
3      0.068196
4      0.068196
         ...
886   -0.031804
887   -0.131804
888   -0.006804
889   -0.044304
890    0.030696
Name: Age, Length: 891, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_rescaled.iloc[:,i] = (df_rescaled.iloc[:,i] - mean) / (max_ - min_)

   Survived    Pclass       Sex       Age      Fare
0 -0.383838  0.345679  0.352413 -0.094304 -0.048707
1  0.616162 -0.654321 -0.647587  0.105696  0.076277
2  0.616162  0.345679 -0.647587 -0.044304 -0.047390
3  0.616162 -0.654321 -0.647587  0.068196  0.040786
4 -0.383838  0.345679  0.352413  0.068196 -0.047146

In [11]:
df_cls.head()

   Survived    Pclass       Sex       Age      Fare
0 -0.383838  0.345679  0.352413 -0.094304 -0.048707
1  0.616162 -0.654321 -0.647587  0.105696  0.076277
2  0.616162  0.345679 -0.647587 -0.044304 -0.047390
3  0.616162 -0.654321 -0.647587  0.068196  0.040786
4 -0.383838  0.345679  0.352413  0.068196 -0.047146

In [12]:
X = df_cls.iloc[:,1:]
Y = df_cls.iloc[:,0]

x = X.to_numpy()
y = Y.to_numpy()
print("=" * 50)
print(x[:10])
print("=" * 50)
print(y[:10])
print(x.shape)
print(y.shape)
print("=" * 50)

==================================================
[[ 0.34567901  0.35241302 -0.09430415 -0.04870737]
 [-0.65432099 -0.64758698  0.10569585  0.07627731]
 [ 0.34567901 -0.64758698 -0.04430415 -0.04738986]
 [-0.65432099 -0.64758698  0.06819585  0.04078587]
 [ 0.34567901  0.35241302  0.06819585 -0.04714587]
 [ 0.34567901  0.35241302 -0.00680415 -0.04634893]
 [-0.65432099  0.35241302  0.30569585  0.03837043]
 [ 0.34567901  0.35241302 -0.34430415 -0.02172277]
 [ 0.34567901 -0.64758698 -0.03180415 -0.04112767]
 [-0.15432099 -0.64758698 -0.19430415 -0.00416414]]
==================================================
[-0.38383838  0.61616162  0.61616162  0.61616162 -0.38383838 -0.38383838
 -0.38383838 -0.38383838  0.61616162  0.61616162]
(891, 4)
(891,)
==================================================

In [14]:
import tensorflow as tf
y = (y >= 0.5).astype(int)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=4, activation="relu"),
    tf.keras.layers.Dense(units=1, activation="sigmoid")
])

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=["accuracy"]
)

model.fit(x, y, epochs=100)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.5859 - loss: 0.6559
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5960 - loss: 0.6405
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6072 - loss: 0.6279
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6061 - loss: 0.6174
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6139 - loss: 0.6081
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6150 - loss: 0.6003
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6173 - loss: 0.5934
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6184 - loss: 0.5875
Epoch 9/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6184 - loss: 0.5820
Epoch 10/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6184 - loss: 0.5773
Epoch 11/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6184 - loss: 0.5727
Epoch 12/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6173 - loss: 0.5686
Epoch 13/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6173 - loss: 0.5648
Epoch 14/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.6162 - loss: 0.5610
Epoch 15/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6139 - loss: 0.5577
Epoch 16/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6139 - loss: 0.5545
Epoch 17/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6139 - loss: 0.5516
Epoch 18/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6768 - loss: 0.5486
Epoch 19/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7845 - loss: 0.5459
Epoch 20/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7901 - loss: 0.5433
Epoch 21/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7924 - loss: 0.5410
Epoch 22/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7924 - loss: 0.5384
Epoch 23/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7924 - loss: 0.5363
Epoch 24/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7924 - loss: 0.5341
Epoch 25/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5321
Epoch 26/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7924 - loss: 0.5301
Epoch 27/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7924 - loss: 0.5283
Epoch 28/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7924 - loss: 0.5266
Epoch 29/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.5249
Epoch 30/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5232
Epoch 31/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.5216
Epoch 32/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7912 - loss: 0.5201
Epoch 33/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5186
Epoch 34/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5171
Epoch 35/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7912 - loss: 0.5157
Epoch 36/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5143
Epoch 37/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.5130
Epoch 38/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5117
Epoch 39/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7901 - loss: 0.5104
Epoch 40/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7901 - loss: 0.5093
Epoch 41/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5081
Epoch 42/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5069
Epoch 43/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5058
Epoch 44/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5046
Epoch 45/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7912 - loss: 0.5035
Epoch 46/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5024
Epoch 47/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.5013
Epoch 48/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7912 - loss: 0.5003
Epoch 49/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7924 - loss: 0.4992
Epoch 50/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7935 - loss: 0.4983
Epoch 51/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7946 - loss: 0.4972
Epoch 52/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4964
Epoch 53/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4955
Epoch 54/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7935 - loss: 0.4947
Epoch 55/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7946 - loss: 0.4937
Epoch 56/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7924 - loss: 0.4929
Epoch 57/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7924 - loss: 0.4921
Epoch 58/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7946 - loss: 0.4912
Epoch 59/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7935 - loss: 0.4904
Epoch 60/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7946 - loss: 0.4897
Epoch 61/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7935 - loss: 0.4889
Epoch 62/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7946 - loss: 0.4881
Epoch 63/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7957 - loss: 0.4874
Epoch 64/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7957 - loss: 0.4868
Epoch 65/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4861
Epoch 66/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7946 - loss: 0.4856
Epoch 67/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7969 - loss: 0.4848
Epoch 68/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7957 - loss: 0.4842
Epoch 69/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7980 - loss: 0.4835
Epoch 70/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7980 - loss: 0.4828
Epoch 71/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7980 - loss: 0.4822
Epoch 72/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7969 - loss: 0.4815
Epoch 73/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7957 - loss: 0.4807
Epoch 74/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7957 - loss: 0.4801
Epoch 75/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7957 - loss: 0.4794
Epoch 76/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4788
Epoch 77/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7946 - loss: 0.4782
Epoch 78/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4776
Epoch 79/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7946 - loss: 0.4772
Epoch 80/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4765
Epoch 81/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7935 - loss: 0.4759
Epoch 82/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4753
Epoch 83/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7946 - loss: 0.4748
Epoch 84/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4743
Epoch 85/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 0.4737
Epoch 86/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7935 - loss: 0.4732
Epoch 87/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7924 - loss: 0.4728
Epoch 88/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7924 - loss: 0.4723
Epoch 89/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7924 - loss: 0.4717
Epoch 90/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7924 - loss: 0.4712
Epoch 91/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.4707
Epoch 92/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.4702
Epoch 93/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7924 - loss: 0.4698
Epoch 94/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7912 - loss: 0.4693
Epoch 95/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7912 - loss: 0.4688
Epoch 96/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.4683
Epoch 97/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.4679
Epoch 98/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7912 - loss: 0.4675
Epoch 99/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7912 - loss: 0.4669
Epoch 100/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.4665

In [ ]:
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=16, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(units=8, activation="relu"),
    tf.keras.layers.Dense(units=1, activation="sigmoid")
])

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"]
)

history = model.fit(x, y, epochs=100, validation_split=0.2, verbose=1)

Epoch 1/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - accuracy: 0.4565 - loss: 0.6966 - val_accuracy: 0.5196 - val_loss: 0.6786
Epoch 2/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.5787 - loss: 0.6749 - val_accuracy: 0.6313 - val_loss: 0.6619
Epoch 3/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.6152 - loss: 0.6597 - val_accuracy: 0.6592 - val_loss: 0.6379
Epoch 4/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.6320 - loss: 0.6373 - val_accuracy: 0.6425 - val_loss: 0.6091
Epoch 5/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.6545 - loss: 0.6168 - val_accuracy: 0.6927 - val_loss: 0.5821
Epoch 6/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7219 - loss: 0.5914 - val_accuracy: 0.8101 - val_loss: 0.5558
Epoch 7/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7514 - loss: 0.5704 - val_accuracy: 0.8045 - val_loss: 0.5288
Epoch 8/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7486 - loss: 0.5513 - val_accuracy: 0.7933 - val_loss: 0.5075
Epoch 9/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7556 - loss: 0.5350 - val_accuracy: 0.7989 - val_loss: 0.4906
Epoch 10/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7584 - loss: 0.5272 - val_accuracy: 0.7989 - val_loss: 0.4790
Epoch 11/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7795 - loss: 0.5161 - val_accuracy: 0.7989 - val_loss: 0.4703
Epoch 12/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7837 - loss: 0.5126 - val_accuracy: 0.7989 - val_loss: 0.4619
Epoch 13/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7865 - loss: 0.5064 - val_accuracy: 0.7989 - val_loss: 0.4564
Epoch 14/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7851 - loss: 0.4912 - val_accuracy: 0.7989 - val_loss: 0.4489
Epoch 15/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7781 - loss: 0.4948 - val_accuracy: 0.7989 - val_loss: 0.4441
Epoch 16/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7753 - loss: 0.4913 - val_accuracy: 0.7989 - val_loss: 0.4382
Epoch 17/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7851 - loss: 0.4875 - val_accuracy: 0.8045 - val_loss: 0.4340
Epoch 18/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7837 - loss: 0.4824 - val_accuracy: 0.7989 - val_loss: 0.4311
Epoch 19/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7809 - loss: 0.4783 - val_accuracy: 0.7989 - val_loss: 0.4284
Epoch 20/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7753 - loss: 0.4926 - val_accuracy: 0.7989 - val_loss: 0.4267
Epoch 21/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7739 - loss: 0.4881 - val_accuracy: 0.8045 - val_loss: 0.4239
Epoch 22/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7823 - loss: 0.4746 - val_accuracy: 0.8101 - val_loss: 0.4210
Epoch 23/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7809 - loss: 0.4801 - val_accuracy: 0.8045 - val_loss: 0.4197
Epoch 24/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7935 - loss: 0.4637 - val_accuracy: 0.8045 - val_loss: 0.4185
Epoch 25/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7753 - loss: 0.4731 - val_accuracy: 0.8101 - val_loss: 0.4164
Epoch 26/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7753 - loss: 0.4658 - val_accuracy: 0.8101 - val_loss: 0.4147
Epoch 27/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7725 - loss: 0.4803 - val_accuracy: 0.8156 - val_loss: 0.4128
Epoch 28/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7767 - loss: 0.4690 - val_accuracy: 0.8101 - val_loss: 0.4117
Epoch 29/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7795 - loss: 0.4636 - val_accuracy: 0.8101 - val_loss: 0.4102
Epoch 30/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7711 - loss: 0.4618 - val_accuracy: 0.8101 - val_loss: 0.4092
Epoch 31/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7921 - loss: 0.4651 - val_accuracy: 0.8101 - val_loss: 0.4088
Epoch 32/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7851 - loss: 0.4643 - val_accuracy: 0.8101 - val_loss: 0.4084
Epoch 33/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7837 - loss: 0.4715 - val_accuracy: 0.8101 - val_loss: 0.4074
Epoch 34/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7823 - loss: 0.4798 - val_accuracy: 0.8101 - val_loss: 0.4048
Epoch 35/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8020 - loss: 0.4590 - val_accuracy: 0.8101 - val_loss: 0.4042
Epoch 36/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7851 - loss: 0.4601 - val_accuracy: 0.8101 - val_loss: 0.4044
Epoch 37/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7851 - loss: 0.4628 - val_accuracy: 0.8101 - val_loss: 0.4037
Epoch 38/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7767 - loss: 0.4748 - val_accuracy: 0.8045 - val_loss: 0.4020
Epoch 39/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7851 - loss: 0.4609 - val_accuracy: 0.8212 - val_loss: 0.4010
Epoch 40/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7753 - loss: 0.4680 - val_accuracy: 0.8268 - val_loss: 0.4000
Epoch 41/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7865 - loss: 0.4545 - val_accuracy: 0.8045 - val_loss: 0.4006
Epoch 42/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7739 - loss: 0.4709 - val_accuracy: 0.8268 - val_loss: 0.3996
Epoch 43/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7753 - loss: 0.4600 - val_accuracy: 0.8268 - val_loss: 0.3985
Epoch 44/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7921 - loss: 0.4525 - val_accuracy: 0.8212 - val_loss: 0.3974
Epoch 45/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7809 - loss: 0.4513 - val_accuracy: 0.8268 - val_loss: 0.3980
Epoch 46/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7963 - loss: 0.4536 - val_accuracy: 0.8212 - val_loss: 0.3961
Epoch 47/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7893 - loss: 0.4532 - val_accuracy: 0.8268 - val_loss: 0.3959
Epoch 48/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7823 - loss: 0.4640 - val_accuracy: 0.8324 - val_loss: 0.3944
Epoch 49/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7640 - loss: 0.4617 - val_accuracy: 0.8212 - val_loss: 0.3953
Epoch 50/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7879 - loss: 0.4561 - val_accuracy: 0.8101 - val_loss: 0.3980
Epoch 51/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7851 - loss: 0.4588 - val_accuracy: 0.8380 - val_loss: 0.3974
Epoch 52/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7865 - loss: 0.4577 - val_accuracy: 0.8324 - val_loss: 0.3962
Epoch 53/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7978 - loss: 0.4473 - val_accuracy: 0.8212 - val_loss: 0.3937
Epoch 54/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7809 - loss: 0.4567 - val_accuracy: 0.8324 - val_loss: 0.3946
Epoch 55/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7837 - loss: 0.4429 - val_accuracy: 0.8324 - val_loss: 0.3926
Epoch 56/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7837 - loss: 0.4598 - val_accuracy: 0.8380 - val_loss: 0.3924
Epoch 57/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7992 - loss: 0.4550 - val_accuracy: 0.8324 - val_loss: 0.3919
Epoch 58/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7851 - loss: 0.4572 - val_accuracy: 0.8380 - val_loss: 0.3922
Epoch 59/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7992 - loss: 0.4511 - val_accuracy: 0.8436 - val_loss: 0.3920
Epoch 60/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7865 - loss: 0.4507 - val_accuracy: 0.8436 - val_loss: 0.3922
Epoch 61/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7837 - loss: 0.4579 - val_accuracy: 0.8380 - val_loss: 0.3917
Epoch 62/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7795 - loss: 0.4657 - val_accuracy: 0.8492 - val_loss: 0.3925
Epoch 63/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7809 - loss: 0.4572 - val_accuracy: 0.8492 - val_loss: 0.3918
Epoch 64/100
 8/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8130 - loss: 0.4072